// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :one
INSERT INTO
  users (id, username, password_hash)
VALUES
  ($1, $2, $3) RETURNING id, username, password_hash, role, created_at, updated_at
`

type AddUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.ID, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByName = `-- name: FindUserByName :one
SELECT
  id, username, password_hash, role, created_at, updated_at
FROM
  users
WHERE
  username = $1
`

func (q *Queries) FindUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
