// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Movie struct {
	ID       uuid.UUID
	Title    string
	Director string
	Year     int32
}

type Review struct {
	ID       uuid.UUID
	UserName string
	Rating   int32
	Comment  sql.NullString
	MovieID  uuid.UUID
}
