// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addMovie = `-- name: AddMovie :one
INSERT INTO
  movies (id, title, director, year)
VALUES
  ($1, $2, $3, $4) RETURNING id, title, director, year
`

type AddMovieParams struct {
	ID       uuid.UUID
	Title    string
	Director string
	Year     int32
}

func (q *Queries) AddMovie(ctx context.Context, arg AddMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, addMovie,
		arg.ID,
		arg.Title,
		arg.Director,
		arg.Year,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.Year,
	)
	return i, err
}

const deleteMovieById = `-- name: DeleteMovieById :exec
DELETE FROM movies
WHERE
  id = $1
`

func (q *Queries) DeleteMovieById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovieById, id)
	return err
}

const getMovieById = `-- name: GetMovieById :one
SELECT
  id, title, director, year
FROM
  movies
WHERE
  id = $1
`

func (q *Queries) GetMovieById(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieById, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.Year,
	)
	return i, err
}

const getMovies = `-- name: GetMovies :many
SELECT
  id, title, director, year
FROM
  movies
`

func (q *Queries) GetMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, getMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
