// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addReview = `-- name: AddReview :one
INSERT INTO
  REVIEWS (id, user_name, rating, comment, movie_id)
VALUES
  ($1, $2, $3, $4, $5) RETURNING id, user_name, rating, comment, movie_id
`

type AddReviewParams struct {
	ID       uuid.UUID
	UserName string
	Rating   int32
	Comment  sql.NullString
	MovieID  uuid.UUID
}

func (q *Queries) AddReview(ctx context.Context, arg AddReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, addReview,
		arg.ID,
		arg.UserName,
		arg.Rating,
		arg.Comment,
		arg.MovieID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Rating,
		&i.Comment,
		&i.MovieID,
	)
	return i, err
}

const getAllReviews = `-- name: GetAllReviews :many
SELECT
  id, user_name, rating, comment, movie_id
FROM
  REVIEWS
`

func (q *Queries) GetAllReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getAllReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Rating,
			&i.Comment,
			&i.MovieID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReviewsByMovieId = `-- name: GetAllReviewsByMovieId :many
SELECT
  id, user_name, rating, comment, movie_id
FROM
  REVIEWS
WHERE
  movie_id = $1
`

func (q *Queries) GetAllReviewsByMovieId(ctx context.Context, movieID uuid.UUID) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getAllReviewsByMovieId, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Rating,
			&i.Comment,
			&i.MovieID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
